namespace Application.DTOs.Insurance;

public record ClaimDto(
    Guid Id,
    string Reason,
    decimal ClaimAmount,
    decimal? ApprovedAmount,
    string Status,
    DateTime SubmittedAt,
    DateTime? ProcessedAt,
    string CustomerName,
    string? ClaimOfficerName,
    string? DocumentUrl,
    string? DocumentHash,
    Guid PolicyId,
    string? Remarks,
    DateTime? ScheduledVideoCallDate,
    string VideoVerificationStatus,
    string? VideoVerificationRemarks,
    double? IncidentLatitude,
    double? IncidentLongitude,
    DateTime? IncidentDate,
    string? CustomerEmail = null,
    string? CustomerPhone = null,
    string? CustomerAddress = null,
    string? PanNumber = null,
    string? PanName = null,
    string? AadhaarReferenceId = null,
    string? AadhaarName = null,
    string? AadhaarAddress = null,
    DateTime? CustomerDateOfBirth = null,
    string? CustomerProfileImageUrl = null,
    List<ClaimTrackingStageDto>? TrackingStages = null
);